package handler

import (
	"github.com/jmoiron/sqlx"

	"github.com/njm2360/vrchat-join-manager/server/internal/repository"
)

// Server implements gen.StrictServerInterface (generated by oapi-codegen).
type Server struct {
	DB        *sqlx.DB
	Analytics *repository.AnalyticsRepo
	Events    *repository.EventsRepo
	Groups    *repository.GroupsRepo
	Instances *repository.InstancesRepo
	Locations *repository.LocationsRepo
	Players   *repository.PlayersRepo
	Worlds    *repository.WorldsRepo
}

func New(db *sqlx.DB) *Server {
	return &Server{
		DB:        db,
		Analytics: repository.NewAnalyticsRepo(db),
		Events:    repository.NewEventsRepo(db),
		Groups:    repository.NewGroupsRepo(db),
		Instances: repository.NewInstancesRepo(db),
		Locations: repository.NewLocationsRepo(db),
		Players:   repository.NewPlayersRepo(db),
		Worlds:    repository.NewWorldsRepo(db),
	}
}
